### ISSUE TITLE
Update to 2.1

### ISSUE THREAD

**Issue by leisegang** [Pr3datorg/XMR-Miner-XMR-Stak-0-donation-level#1]
Could you update this to the latest version ?

**Comment by Pr3datorg** [comment]
hey bud - it is 2.1.0 - currently only made it for AMD - working on the AIO version - well its complete but I am just in the process of testing and will upload soon.

**Comment by Pr3datorg** [comment]
https://github.com/Pr3datorg/XMR-Miner-XMR-Stak-0-donation-level/releases/tag/2.1.0
New release should resolve your problems.

**Comment by leisegang** [comment]
have you found where they have added the donation wallet? And is this changable? I install miners from a lot of friends and want a donation to go to me. not them. is this possible?

**Comment by Pr3datorg** [comment]
Yes it is with in one of the console.sh files - before you compile the original you edit this file to change the pools - as I don't have my own pool putting it to 0% was easier - although i believe very slight and I mean slight drop by like 1 or 2 hashs.
